# Generated by Django 5.2.8 on 2025-11-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_waitlistentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
